#pragma config(Motor,  port1,           motorName,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Above is the motor/sensor setup. We only need one motor (we named it 'motorName').

task main() //'Task main' is where you put the code that is to run on startup
{

int sec=1; //This is a varible of the integer type. It's name is 'sec', and it represents the amount of seconds the motor is on.

motor[motorName]=127; //Sets the speed of motor, 'motorName', to 127.

wait1Msec(sec*1000); //Pauses the code for (sec*1000) miliseconds.

motor[motorName]=0; //Sets the speed of motor, 'motorName', to 0 (turning it off).

}
